name: Auto Commit and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '*/1 * * * *' 

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Auto commit changes
        run: |
          git add .
          git commit -m "Auto commit changes from workflow" || echo "No changes to commit"
          git push
