name: Auto Commit and Push

on:
  schedule:
    - cron: '*/1 * * * *'
  push:
    branches:
      - main

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup git authentication
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/abdarrhmanessetaoui/Curreny-Converter-App.git

      - name: Auto commit changes
        run: |
          git add .
          git commit -m "Auto commit changes from workflow" || echo "No changes to commit"
          git push origin main
